#!/usr/bin/env bash
#Install nginx on your web-01 server
#Nginx should be listening on port 80
apt-get -y update
apt-get -y install nginx
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/defult
ufw allow 'Nginx HTTP'
echo Holberton School > /var/www/html/index.nginx-debian.html
service nginx start
